name: SoapUI Docker Image CI

on:
  push:
    branches: [ "develop" ]

jobs:

  build:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Docker Login
      run: docker login -u ${{secrets.DOCKHUB_UID}} -p ${{secrets.DOCKHUB_PWD}}
    - name: Build the Docker image
      run: docker build --build-arg CACHEBUST=$(date +"%s") --file Dockerfile --tag itzmedinesh/soapui-mock .
    - name: Push image to docker hub
      run: docker push itzmedinesh/soapui-mock:latest

  deploy:
    needs: build
    runs-on: [amazon-linux-2023]
    steps:
      - name: Docker Login
        run: sudo docker login -u ${{secrets.DOCKHUB_UID}} -p ${{secrets.DOCKHUB_PWD}}
      - name: Pull image from docker hub
        run: sudo docker pull itzmedinesh/soapui-mock:latest
      - name: Delete container if exists
        run: sudo docker rm -f soapui-mock-container
      - name: Run as container
        run: sudo docker run -d -p 7000:7000 --name soapui-mock-container itzmedinesh/soapui-mock