name: SoapUI Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Docker Login
      run: echo ${{ secrets.DOCKHUB_PWD }} | docker login -u ${{ secrets.DOCKHUB_UID }} --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag soapui-mock:$(date +%s)
    - name: Push image to docker hub
      run: docker push itzmedinesh/soapui-mock:latest